version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    image: dvlance/reminder-backend
    restart: always

    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: ${PORT}
  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx/certbot:/var/www/html
      - certbot-etc:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/html --email diego@dvlance.com --agree-tos --no-eff-email --staging -d reminder.dvlance.com
    volumes:
      - ./nginx/certbot:/var/www/html
      - certbot-etc:/etc/letsencrypt
    depends_on:
      - nginx
volumes:
  certbot-etc:
